name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "Sin empezar"

  [[processes.tasks]]
  id = "awp9gi4jf4vt71nigbozkbzj"
  title = "ScoreBoard"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "En proceso"

  [[processes.tasks]]
  id = "uo90jwh31swuglgzixu15719"
  title = "Inicio sesion jugador"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "am5jj29h0972smxgcr2zqgxw"
  title = "Comprobar metodos estáticos"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "aeg4zub92ulnat9jhlp3gvty"
  title = "Control Visibidad Propiedades"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "High"
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Completadas"

  [[processes.tasks]]
  id = "exf7wixvu3iyyakffdi07xga"
  title = "implementar pygame"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "dn0v3forr7g9n1bmfpfwsi69"
  title = "Mejora de la ruleta"
  description = "<p>Añadir mas gajos especiales</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  priority = "Normal"
  linkCommits = [ ]

    [[processes.tasks.checkList]]
    id = "otxjj6lm0f1rmjjff87xkdav"
    title = "Printeo de las selecciones"
    completed = true

    [[processes.tasks.checkList]]
    id = "dqmvedsf6qtk410tybcqyq86"
    title = "Gajo x2"
    completed = true

    [[processes.tasks.checkList]]
    id = "bmwuf64y34cdvhm4an3iqkc8"
    title = "Gajo 1/2"
    completed = true

    [[processes.tasks.checkList]]
    id = "dvzsl869yzmjakdhh95f53r4"
    title = "Gajo all vowels"
    completed = true

    [[processes.tasks.checkList]]
    id = "p6d4sv1bwff181ztkylc00tl"
    title = "mas?"
    completed = false

  [[processes.tasks]]
  id = "y7iw8hsksae635wocjg7bu6k"
  title = "Printear el panel en todo momento"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "High"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "o0s2j52ykwmt7ze086k6spr1"
  title = "añadir espacios para igualar las filas"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "v5li6ps12ukktmsbqzbiw85k"
  title = "Juntar funcion vocal y consonante"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "rr7b5j5e11ntc65bw44orplh"
  title = "preguntas aleatorias"
  description = "eleccion de preguntas aleatorias"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "asrxxnystnst7fzbddvuxlry"
  title = "Finalizar ronda panel resuelto"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "kmqw04cuza6j4gbkj2l5hctu"
  title = "Registrador de paneles"
  description = "<p>Un cliente para poder añadir preguntas nuevas</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "Low"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "bfmypci4i4piw1a2m21han8i"
  title = "preguntar por letra"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "s3sal9ct7zhcek2qqp0qgbbp"
  title = "Puntuacion al resolver un panel"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "High"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "tbaal8dr8uxrckvv4whehqgu"
  title = "juego a varias rondas"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "pe04nu8dw2g7z771bkeqhl55"
  title = "Cambio de turnos"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "High"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "acx63xen65ux0bgm3ou0h189"
  title = "Ciclo de juego"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "High"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "uqavhr1cw5sy4ulf1wwqy83c"
  title = "Menu de Inicio"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "eqgsb2i1v2r2yhtlcw1g2wgl"
name = "Descartes version terminal"
tasks = [ ]
