name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "kmqw04cuza6j4gbkj2l5hctu"
  title = "Registrador de paneles"
  description = "Un cliente para poder añadir preguntas nuevas"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "bfmypci4i4piw1a2m21han8i"
  title = "preguntar por letra"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "tbaal8dr8uxrckvv4whehqgu"
  title = "juego a varias rondas"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "vf93e7vn3enfmrwhw29rwqei"
  title = "Implementar sockets"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "acx63xen65ux0bgm3ou0h189"
  title = "Ciclo de juego"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "rr7b5j5e11ntc65bw44orplh"
  title = "preguntas aleatorias"
  description = "eleccion de preguntas aleatorias"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "uqavhr1cw5sy4ulf1wwqy83c"
  title = "Menu de Inicio"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
